reset
as test_alu test_alu
ld test_alu
dump -readmemh x0000 xFFFF test_alu.hex
trace on test_alu.trace
break set END_LABEL
continue

reset
as test_mem test_mem
ld test_mem
dump -readmemh x0000 xFFFF test_mem.hex
trace on test_mem.trace
break set END_LABEL
continue

reset
as test_br test_br
ld test_br
dump -readmemh x0000 xFFFF test_br.hex
trace on test_br.trace
break set END_LABEL
continue

reset
as test_all test_all
ld test_all
dump -readmemh x0000 xFFFF test_all.hex
trace on test_all.trace
break set END_LABEL
continue

reset
as test_ld_br test_ld_br
ld test_ld_br
dump -readmemh x0000 xFFFF test_ld_br.hex
trace on test_ld_br.trace
break set END_LABEL
continue


quit
